name: Deploy Workspace API to Azure

on:
  push:
    branches: [ "main" ] 

permissions:
  id-token: write 
  packages: write 
  contents: read

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' 

    - name: Build and Test
      run: |
        dotnet build
        dotnet test

    #  Pipeline authentication without stored secrets (OIDC)
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set lower case image repository
      run: |
        echo "IMAGE_TAG=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/workspace-task-api" >> $GITHUB_ENV

    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef

    - name: Allow GitHub Runner IP to Azure SQL
      run: |
        RUNNER_IP=$(curl -s https://api.ipify.org)
        echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
        az sql server firewall-rule create --resource-group rg-workspace-api-dev --server sqlserver-islam-dev-002 --name GitHubRunnerRule --start-ip-address $RUNNER_IP --end-ip-address $RUNNER_IP

    # Migrations in a pipeline
    # - name: Apply Database Migrations
    #   env:
    #     ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
    #   run: |
    #     CLEAN_CONN="${ConnectionStrings__DefaultConnection//\"/}"
    #     export ConnectionStrings__DefaultConnection="$CLEAN_CONN"
    #     dotnet ef database update \
    #       --project BookCatalog.Infrastructure \
    #       --startup-project BookCatalog.API \
    #       --connection "$CLEAN_CONN"
    - name: Apply Database Migrations
      run: |
        DB_TOKEN=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)
        dotnet ef database update \
          --project BookCatalog.Infrastructure \
          --startup-project BookCatalog.API \
          --connection "Server=tcp:sqlserver-islam-dev-002.database.windows.net,1433;Initial Catalog=sqldb-workspace-api-002;Encrypt=True;TrustServerCertificate=False;ActiveDirectory Token=$DB_TOKEN;"

    - name: Remove GitHub Runner IP from Azure SQL
      if: always()
      run: |
        az sql server firewall-rule delete --resource-group rg-workspace-api-dev --server sqlserver-islam-dev-002 --name GitHubRunnerRule

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Image tagging, digests and versioning (No "latest" tag)
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_TAG }}:${{ github.sha }}

    # Deploy the exact artifact you tested (Using explicit SHA)
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name ca-bookcatalog-api-dev-003 \
          --resource-group rg-workspace-api-dev \
          --image ${{ env.IMAGE_TAG }}:${{ github.sha }} \
          --set-env-vars ASPNETCORE_ENVIRONMENT=Development ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}"